@startuml
package factory {
  package abstract_factory {
    abstract class PizzaStore
    class NYPizzaStore
    class ChicagoPizzaStore
    abstract class Pizza
    class CheesePizza
    class ClamPizza
    class VeggiePizza
    class PepperoniPizza
    abstract class PizzaIngredientFactory
    class NYPizzaIngredientFactory
    class ChicagoPizzaIngredientFactory
    class NYStylePepperoniPizzaIngredientFactory
    class ChicagoStylePepperoniPizzaIngredientFactory
    class Dough
    class Sauce
    class Cheese
    class Clams
    abstract class Pepperoni
    class NYStylePepperoni
    class ChicagoStylePepperoni
    class Veggies

    PizzaStore <|-- NYPizzaStore
    PizzaStore <|-- ChicagoPizzaStore
    PizzaStore --> Pizza
    Pizza <|-- CheesePizza
    Pizza <|-- ClamPizza
    Pizza <|-- VeggiePizza
    Pizza <|-- PepperoniPizza
    Pizza --> PizzaIngredientFactory
    PizzaIngredientFactory <|-- NYPizzaIngredientFactory
    PizzaIngredientFactory <|-- ChicagoPizzaIngredientFactory
    PizzaIngredientFactory <|-- NYStylePepperoniPizzaIngredientFactory
    PizzaIngredientFactory <|-- ChicagoStylePepperoniPizzaIngredientFactory
    NYPizzaIngredientFactory --> Dough
    NYPizzaIngredientFactory --> Sauce
    NYPizzaIngredientFactory --> Cheese
    NYPizzaIngredientFactory --> Clams
    NYPizzaIngredientFactory --> Pepperoni
    NYStylePepperoniPizzaIngredientFactory --> NYStylePepperoni
    ChicagoPizzaIngredientFactory --> Dough
    ChicagoPizzaIngredientFactory --> Sauce
    ChicagoPizzaIngredientFactory --> Cheese
    ChicagoPizzaIngredientFactory --> Clams
    ChicagoPizzaIngredientFactory --> Pepperoni
    ChicagoStylePepperoniPizzaIngredientFactory --> ChicagoStylePepperoni
    NYPizzaIngredientFactory --> Veggies
    ChicagoPizzaIngredientFactory --> Veggies
    NYStylePepperoniPizzaIngredientFactory --> Veggies
    ChicagoStylePepperoniPizzaIngredientFactory --> Veggies
  }
}
@enduml
